export const FETCH_POSTS="_FETCH_POSTS"
export const NEW_POSTS="_NEW_POSTS"
export const INSERT_POST='_INSERT_POST'
export const NEW_DISCUSSION="_NEW_DISCUSSION"
export const EXPAND_DISCUSSION="_EXPAND_DISCUSSION"



export const LOGIN_SUCCESS ="_LOGIN_SUCCESS"
export const LOGIN_FAILED ="_LOGIN_FAILED"
export const IS_SIGNED_USER="_IS_SIGNED_USER"

export const SCREEN_CHANGED="_SCREEN_CHANGED"



export const PANEL_NEW_POST_ENTRY_PROP_CHANGE="_PANEL_NEW_POST_ENTRY_PROP_CHANGE"