class ScreenIDs{
}

export const SCREEN_ID_HOME="_SCREEN_ID_HOME"
export const SCREEN_ID_CREATE_NEW_DISCUSSION="_SCREEN_ID_CREATE_NEW_DISCUSSION"
export const SCREEN_ID_LOGIN="_SCREEN_ID_LOGIN"
export const SCREEN_ID_DISCUSSION="_SCREEN_ID_DISCUSSION"

export default ScreenIDs