class ScreenIDs{
}

export const SCREEN_ID_HOME="_SCREEN_ID_HOME"
export const SCREEN_ID_CREATE_NEW_DISCUSSION="_SCREEN_ID_CREATE_NEW_DISCUSSION"
export const SCREEN_ID_LOGIN="_SCREEN_ID_LOGIN"
export const SCREEN_ID_DISCUSSION="_SCREEN_ID_DISCUSSION"


export const PANEL_ID_NEW_POST_ENTRY='_PANEL_ID_NEW_POST_ENTRY'

export default ScreenIDs